name: CD Pipeline

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - uses: actions/checkout@v4

      # Set up SSH key
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SERVER_SSH_KEY }}

      # Log in to Docker Hub
      - name: Docker Hub Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      # Build and push Docker images with caching
      - name: Build & Push Docker Image
        run: |
          docker build \
            --cache-from ${{ secrets.DOCKER_HUB_USERNAME }}/movie-backend:latest \
            -t ${{ secrets.DOCKER_HUB_USERNAME }}/movie-backend:${{ github.sha }} .
          docker tag ${{ secrets.DOCKER_HUB_USERNAME }}/movie-backend:${{ github.sha }} ${{ secrets.DOCKER_HUB_USERNAME }}/movie-backend:latest
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/movie-backend:${{ github.sha }}
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/movie-backend:latest

      # Deploy full docker-compose stack and run migrations
      - name: Deploy docker-compose stack with migrations
        run: |
          ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
            set -e
            cd /home/${{ secrets.SERVER_USER }}/project_nexus/alx-project-nexus

            # Pull latest code
            git fetch --all
            git reset --hard origin/main

            # Pull updated images
            docker-compose pull

            # Build only changed services
            docker-compose build

            # Run database migrations for Django
            docker-compose run --rm web python manage.py migrate --noinput

            # Restart all services
            docker-compose up -d

            # Optional cleanup
            docker image prune -f
          EOF
